### ISSUE TITLE
Unsupported asset class: "Cash Collateral".

### ISSUE THREAD

**Issue by ranisalt** [KonishchevDmitry/investments#58]
First of all, thanks for the app, it's really helpful and I've been using it for the past year.

I'm trying to import a statement from Interactive Brokers, but I get the following error:

```
E: Error while reading "/home/rsa/.investments/statements/U4182902_20220103_20220201.csv" broker statement: Failed to parse ("Net Asset Value", "Data", "Cash Collateral", "0", "1124", "0", "1124", "1124") record: Unsupported asset class: "Cash Collateral".
```

**Comment by KonishchevDmitry** [comment]
Hi! What is it in your case? You borrowed some cash and bought stocks for it or it's a cash collateral for your stocks which IB borrowed due to Stock Yield Enhancement Program? How this number affects other parts of your statement?

**Comment by ranisalt** [comment]
@KonishchevDmitry it is the second, I have enabled the Stock Yield Enhancement Program last month.

If I remove that line, I then get:
```Failed to parse ("Net Asset Value", "Data", "Securities Lent", "0", "0", "-1124", "-1124", "-1124") record: Unsupported asset class: "Securities Lent".```

I'm not sure how to check how it affects other parts of my statement, those lines are one right above the other.

**Comment by KonishchevDmitry** [comment]
Can you send me your statement (or significant parts of it) to konishchev@gmail.com?

If you can't do this due to privacy reasons, I need more information to support it properly:
1. At this point we know that there are two new asset types: `Cash Collateral` and `Securities Lent`. `1124` - what is it? Shares or USD? (I suppose, USD)
2. Do they decrease `Stock` part? I need to know it, because I use `Net Asset Value` information for calculation of annual cash/assets flows (Russian tax statement specific). So I need to understand what to do with them: just ignore, or add up to total stock value – https://github.com/KonishchevDmitry/investments/blob/974080c0cd65e5cec3a5a6fc7aca421530ceb78c/src/broker_statement/ib/summary.rs#L67-L80
3. What happens when you remove these lines? Parsing succedes? If not, what else you have to remove to make it work?
4. What does `Open Positions` show for the lent stocks?
5. I suppose that the result income should be listed in `Interest` section. What does it contain?
6. Does `cash-flow` command show any warnings (yes, sorry - its output in Russian, but warnings will be in English and colored).

**Comment by ranisalt** [comment]
I sent you the statements via email. Unfortunately, I wouldn't be able to answer most of these questions.

**Comment by KonishchevDmitry** [comment]
Thanks! You haven't received the interest yet (it's only pending yet), so there is no any information about it in `Interest` section, but it looks like it won't be a problem for me to support your statement, so I'll do it as soon as I'll have a free time slot for it.

**Comment by KonishchevDmitry** [comment]
Supported in v4.3.2
